### PR TITLE
Add Interface for UsernameUpdatedEvent to make testing possible

### PR DESCRIPTION
**Pull request by jaimybroere**
It's currently not possible to test against the UsernameUpdatedEvent because it's final.

### CODE REVIEW

**Comment by jaapromijn** [comment]
You don't _have_ to mock it though. 
```php
$user    = $this->createMock(UserInterface::class); 
$event = new UsernameUpdatedEvent($user);
```

**Comment by jaimybroere** [comment]
Because I can't create a mock of a final class

**Comment by RonRademaker** [comment]
Any good event is just a DTO, so why mock it instead of just creating a new one? Creating DTO's should be easy and not require any difficult dependencies.

**Comment by jaimybroere** [comment]
Yes, @jaapromijn just explained this to me. Thanks both!

**Pull request closed without merging**
